CANTON_SET = {
    "ncc",
    "amberieu en bugey",
    "attignat",
    "bellegarde sur valserine",
    "belley",
    "bourg en bresse 1",
    "bourg en bresse 2",
    "ceyzeriat",
    "chatillon sur chalaronne",
    "gex",
    "hauteville lompnes",
    "lagnieu",
    "meximieux",
    "miribel",
    "nantua",
    "oyonnax",
    "pont d'ain",
    "replonges",
    "saint etienne du bois",
    "saint genis pouilly",
    "thoiry",
    "trevoux",
    "villars les dombes",
    "vonnas",
    "bohain en vermandois",
    "chateau thierry",
    "chauny",
    "essomes sur marne",
    "fere en tardenois",
    "guignicourt",
    "guise",
    "hirson",
    "laon 1",
    "laon 2",
    "marle",
    "ribemont",
    "saint quentin 1",
    "saint quentin 2",
    "saint quentin 3",
    "soissons 1",
    "soissons 2",
    "tergnier",
    "vervins",
    "vic sur aisne",
    "villers cotterets",
    "bellerive sur allier",
    "bourbon l'archambault",
    "commentry",
    "cusset",
    "dompierre sur besbre",
    "gannat",
    "huriel",
    "lapalisse",
    "montlucon 1",
    "montlucon 2",
    "montlucon 3",
    "montlucon 4",
    "moulins 1",
    "moulins 2",
    "saint pourcain sur sioule",
    "souvigny",
    "vichy 1",
    "vichy 2",
    "yzeure",
    "barcelonnette",
    "castellane",
    "chateau arnoux saint auban",
    "digne les bains 1",
    "digne les bains 2",
    "forcalquier",
    "manosque 1",
    "manosque 2",
    "manosque 3",
    "oraison",
    "reillanne",
    "riez",
    "seyne",
    "sisteron",
    "valensole",
    "argentiere la bessee",
    "briancon 1",
    "briancon 2",
    "chorges",
    "embrun",
    "gap 1",
    "gap 2",
    "gap 3",
    "gap 4",
    "guillestre",
    "laragne monteglin",
    "saint bonnet en champsaur",
    "serres",
    "tallard",
    "veynes",
    "antibes 1",
    "antibes 2",
    "antibes 3",
    "beausoleil",
    "cagnes sur mer 1",
    "cagnes sur mer 2",
    "cannes 1",
    "cannes 2",
    "cannet",
    "contes",
    "grasse 1",
    "grasse 2",
    "mandelieu la napoule",
    "menton",
    "nice 1",
    "nice 2",
    "nice 3",
    "nice 4",
    "nice 5",
    "nice 6",
    "nice 7",
    "nice 8",
    "nice 9",
    "tourrette levens",
    "valbonne",
    "vence",
    "villeneuve loubet",
    "annonay 1",
    "annonay 2",
    "aubenas 1",
    "aubenas 2",
    "bourg saint andeol",
    "haut eyrieux",
    "guilherand granges",
    "haut vivarais",
    "pouzin",
    "privas",
    "sarras",
    "berg helvie",
    "haute ardeche",
    "tournon sur rhone",
    "vallon pont d'arc",
    "cevennes ardechoises",
    "rhone eyrieux",
    "attigny",
    "bogny sur meuse",
    "carignan",
    "charleville mezieres 1",
    "charleville mezieres 2",
    "charleville mezieres 3",
    "charleville mezieres 4",
    "chateau porcien",
    "givet",
    "nouvion sur meuse",
    "rethel",
    "revin",
    "rocroi",
    "sedan 1",
    "sedan 2",
    "sedan 3",
    "signy l'abbaye",
    "villers semeuse",
    "vouziers",
    "haute ariege",
    "arize leze",
    "couserans est",
    "couserans ouest",
    "foix",
    "mirepoix",
    "pamiers 1",
    "pamiers 2",
    "pays d'olmes",
    "portes d'ariege",
    "portes du couserans",
    "sabarthes",
    "val d'ariege",
    "aix en othe",
    "arcis sur aube",
    "bar sur aube",
    "bar sur seine",
    "brienne le chateau",
    "creney pres troyes",
    "nogent sur seine",
    "riceys",
    "romilly sur seine",
    "saint andre les vergers",
    "saint lye",
    "troyes 1",
    "troyes 2",
    "troyes 3",
    "troyes 4",
    "troyes 5",
    "vendeuvre sur barse",
    "piege au razes",
    "carcassonne 1",
    "carcassonne 2",
    "carcassonne 3",
    "bassin chaurien",
    "basses plaines de l'aude",
    "corbieres",
    "lezignanais",
    "region limouxine",
    "malepere a la montagne noire",
    "narbonne 1",
    "narbonne 2",
    "narbonne 3",
    "haute vallee de l'aude",
    "haut minervois",
    "sud minervois",
    "corbieres mediterranee",
    "montagne d'alaric",
    "vallee de l'orbiel",
    "aubrac et carladez",
    "aveyron et tarn",
    "causse comtal",
    "causses rougiers",
    "ceor segala",
    "enne et alzou",
    "lot et dourdou",
    "lot et montbazinois",
    "lot et palanges",
    "lot et truyere",
    "millau 1",
    "millau 2",
    "monts du requistanais",
    "nord levezou",
    "raspes et levezou",
    "rodez 1",
    "rodez 2",
    "rodez onet",
    "saint affrique",
    "tarn et causses",
    "vallon",
    "villefranche de rouergue",
    "villeneuvois et villefranchois",
    "aix en provence 1",
    "aix en provence 2",
    "allauch",
    "arles",
    "aubagne",
    "berre l'etang",
    "chateaurenard",
    "ciotat",
    "gardanne",
    "istres",
    "marignane",
    "marseille 1",
    "marseille 2",
    "marseille 3",
    "marseille 4",
    "marseille 5",
    "marseille 6",
    "marseille 7",
    "marseille 8",
    "marseille 9",
    "marseille 10",
    "marseille 11",
    "marseille 12",
    "martigues",
    "pelissanne",
    "salon de provence 1",
    "salon de provence 2",
    "trets",
    "vitrolles",
    "aunay sur odon",
    "bayeux",
    "bretteville l'orgueilleuse",
    "cabourg",
    "caen 1",
    "caen 2",
    "caen 3",
    "caen 4",
    "caen 5",
    "conde sur noireau",
    "courseulles sur mer",
    "evrecy",
    "falaise",
    "herouville saint clair",
    "honfleur deauville",
    "ifs",
    "lisieux",
    "livarot",
    "mezidon canon",
    "ouistreham",
    "pont l'eveque",
    "thury harcourt",
    "trevieres",
    "troarn",
    "vire",
    "arpajon sur cere",
    "aurillac 1",
    "aurillac 2",
    "aurillac 3",
    "mauriac",
    "maurs",
    "murat",
    "naucelles",
    "neuveglise",
    "riom es montagnes",
    "saint flour 1",
    "saint flour 2",
    "saint paul des landes",
    "vic sur cere",
    "ydes",
    "angouleme 1",
    "angouleme 2",
    "angouleme 3",
    "boeme echelle",
    "boixe et manslois",
    "charente bonnieure",
    "charente champagne",
    "charente nord",
    "charente sud",
    "charente vienne",
    "cognac 1",
    "cognac 2",
    "couronne",
    "gond pontouvre",
    "jarnac",
    "touvre et braconne",
    "tude et lavalette",
    "val de nouere",
    "val de tardoire",
    "aytre",
    "chaniers",
    "chatelaillon plage",
    "ile d'oleron",
    "ile de re",
    "jarrie",
    "jonzac",
    "lagord",
    "marans",
    "marennes",
    "matha",
    "pons",
    "rochefort",
    "rochelle 1",
    "rochelle 2",
    "rochelle 3",
    "royan",
    "saint jean d'angely",
    "saint porchaire",
    "saintes",
    "saintonge estuaire",
    "saujon",
    "surgeres",
    "thenac",
    "tonnay charente",
    "tremblade",
    "trois monts",
    "aubigny sur nere",
    "avord",
    "bourges 1",
    "bourges 2",
    "bourges 3",
    "bourges 4",
    "charost",
    "chateaumeillant",
    "dun sur auron",
    "guerche sur l'aubois",
    "mehun sur yevre",
    "saint amand montrond",
    "saint doulchard",
    "saint germain du puy",
    "saint martin d'auxigny",
    "sancerre",
    "trouy",
    "vierzon 1",
    "vierzon 2",
    "allassac",
    "argentat",
    "brive la gaillarde 1",
    "brive la gaillarde 2",
    "brive la gaillarde 3",
    "brive la gaillarde 4",
    "egletons",
    "haute dordogne",
    "malemort sur correze",
    "midi correzien",
    "naves",
    "plateau de millevaches",
    "saint pantaleon de larche",
    "sainte fortunade",
    "seilhac monedieres",
    "tulle",
    "ussel",
    "uzerche",
    "yssandonnais",
    "ajaccio 1",
    "ajaccio 2",
    "ajaccio 3",
    "ajaccio 4",
    "ajaccio 5",
    "bavella",
    "grand sud",
    "gravona prunelli",
    "sartenais valinco",
    "sevi sorru cinarca",
    "taravo ornano",
    "bastia 1",
    "bastia 2",
    "bastia 3",
    "bastia 4",
    "biguglia nebbio",
    "borgo",
    "calvi",
    "cap corse",
    "casinca fumalto",
    "castagniccia",
    "corte",
    "fiumorbo castello",
    "ghisonaccia",
    "golo morosaglia",
    "ile rousse",
    "arnay le duc",
    "auxonne",
    "beaune",
    "brazey en plaine",
    "chatillon sur seine",
    "chenove",
    "chevigny saint sauveur",
    "dijon 1",
    "dijon 2",
    "dijon 3",
    "dijon 4",
    "dijon 5",
    "dijon 6",
    "fontaine les dijon",
    "genlis",
    "is sur tille",
    "ladoix serrigny",
    "longvic",
    "montbard",
    "nuits saint georges",
    "saint apollinaire",
    "semur en auxois",
    "talant",
    "begard",
    "broons",
    "callac",
    "dinan",
    "guingamp",
    "lamballe",
    "lannion",
    "lanvallay",
    "loudeac",
    "mur de bretagne",
    "paimpol",
    "perros guirec",
    "plaintel",
    "plancoet",
    "plelo",
    "plenee jugon",
    "pleneuf val andre",
    "plerin",
    "pleslin trigavou",
    "plestin les greves",
    "ploufragan",
    "plouha",
    "rostrenen",
    "saint brieuc 1",
    "saint brieuc 2",
    "tregueux",
    "treguier",
    "ahun",
    "aubusson",
    "auzances",
    "bonnat",
    "bourganeuf",
    "boussac",
    "dun le palestel",
    "evaux les bains",
    "felletin",
    "gouzon",
    "grand bourg",
    "gueret 1",
    "gueret 2",
    "saint vaury",
    "souterraine",
    "bergerac 1",
    "bergerac 2",
    "brantome",
    "coulounieix chamiers",
    "haut perigord noir",
    "isle loue auvezere",
    "isle manoire",
    "lalinde",
    "montpon menesterol",
    "pays de la force",
    "pays de montaigne et gurson",
    "perigord central",
    "perigord vert nontronnais",
    "perigueux 1",
    "perigueux 2",
    "riberac",
    "saint astier",
    "sarlat la caneda",
    "sud bergeracois",
    "terrasson lavilledieu",
    "thiviers",
    "trelissac",
    "vallee dordogne",
    "vallee de l'isle",
    "vallee de l'homme",
    "audincourt",
    "baume les dames",
    "bavans",
    "besancon 1",
    "besancon 2",
    "besancon 3",
    "besancon 4",
    "besancon 5",
    "besancon 6",
    "bethoncourt",
    "frasne",
    "maiche",
    "montbeliard",
    "morteau",
    "ornans",
    "pontarlier",
    "saint vit",
    "valdahon",
    "valentigney",
    "bourg de peage",
    "crest",
    "dieulefit",
    "diois",
    "drome des collines",
    "grignan",
    "loriol sur drome",
    "montelimar 1",
    "montelimar 2",
    "nyons et baronnies",
    "romans sur isere",
    "saint vallier",
    "tain l'hermitage",
    "tricastin",
    "valence 1",
    "valence 2",
    "valence 3",
    "valence 4",
    "vercors monts du matin",
    "andelys",
    "bernay",
    "beuzeville",
    "bourg achard",
    "bourgtheroulde infreville",
    "breteuil",
    "brionne",
    "conches en ouche",
    "evreux 1",
    "evreux 2",
    "evreux 3",
    "gaillon",
    "gisors",
    "louviers",
    "neubourg",
    "pacy sur eure",
    "pont audemer",
    "pont de l'arche",
    "romilly sur andelle",
    "saint andre de l'eure",
    "val de reuil",
    "verneuil sur avre",
    "vernon",
    "anet",
    "auneau",
    "brou",
    "chartres 1",
    "chartres 2",
    "chartres 3",
    "chateaudun",
    "dreux 1",
    "dreux 2",
    "epernon",
    "illiers combray",
    "luce",
    "nogent le rotrou",
    "saint lubin des joncherets",
    "voves",
    "brest 1",
    "brest 2",
    "brest 3",
    "brest 4",
    "brest 5",
    "briec",
    "carhaix plouguer",
    "concarneau",
    "crozon",
    "douarnenez",
    "fouesnant",
    "guipavas",
    "landerneau",
    "landivisiau",
    "lesneven",
    "moelan sur mer",
    "morlaix",
    "plabennec",
    "ploneour lanvern",
    "plouigneau",
    "pont de buis les quimerch",
    "pont l'abbe",
    "quimper 1",
    "quimper 2",
    "quimperle",
    "saint pol de leon",
    "saint renan",
    "aigues mortes",
    "ales 1",
    "ales 2",
    "ales 3",
    "bagnols sur ceze",
    "beaucaire",
    "calvisson",
    "grand combe",
    "marguerittes",
    "nimes 1",
    "nimes 2",
    "nimes 3",
    "nimes 4",
    "pont saint esprit",
    "quissac",
    "redessan",
    "roquemaure",
    "rousson",
    "saint gilles",
    "uzes",
    "vauvert",
    "vigan",
    "villeneuve les avignon",
    "auterive",
    "bagneres de luchon",
    "blagnac",
    "castanet tolosan",
    "castelginest",
    "cazeres",
    "escalquens",
    "leguevin",
    "muret",
    "pechbonnieu",
    "plaisance du touch",
    "portet sur garonne",
    "revel",
    "saint gaudens",
    "toulouse 1",
    "toulouse 2",
    "toulouse 3",
    "toulouse 4",
    "toulouse 5",
    "toulouse 6",
    "toulouse 7",
    "toulouse 8",
    "toulouse 9",
    "toulouse 10",
    "toulouse 11",
    "tournefeuille",
    "villemur sur tarn",
    "adour gersoise",
    "armagnac tenareze",
    "astarac gimone",
    "auch 1",
    "auch 2",
    "auch 3",
    "baise armagnac",
    "fezensac",
    "fleurance lomagne",
    "gascogne auscitaine",
    "gimone arrats",
    "grand bas armagnac",
    "isle jourdain",
    "lectoure lomagne",
    "mirande astarac",
    "pardiac riviere basse",
    "val de save",
    "andernos les bains",
    "bordeaux 1",
    "bordeaux 2",
    "bordeaux 3",
    "bordeaux 4",
    "bordeaux 5",
    "bouscat",
    "brede",
    "cenon",
    "coteaux de dordogne",
    "creon",
    "entre deux mers",
    "estuaire",
    "gujan mestras",
    "landes des graves",
    "libournais fronsadais",
    "lormont",
    "merignac 1",
    "merignac 2",
    "nord gironde",
    "nord libournais",
    "nord medoc",
    "pessac 1",
    "pessac 2",
    "portes du medoc",
    "presqu'ile",
    "reolais et les bastides",
    "saint medard en jalles",
    "sud gironde",
    "sud medoc",
    "talence",
    "teste de buch",
    "villenave d'ornon",
    "agde",
    "beziers 1",
    "beziers 2",
    "beziers 3",
    "cazouls les beziers",
    "clermont l'herault",
    "cres",
    "frontignan",
    "gignac",
    "lattes",
    "lodeve",
    "lunel",
    "mauguio",
    "meze",
    "montpellier 1",
    "montpellier 2",
    "montpellier 3",
    "montpellier 4",
    "montpellier 5",
    "montpellier   castelnau le lez",
    "pezenas",
    "pignan",
    "saint gely du fesc",
    "saint pons de thomieres",
    "sete",
    "antrain",
    "bain de bretagne",
    "betton",
    "bruz",
    "chateaugiron",
    "combourg",
    "dol de bretagne",
    "fougeres 1",
    "fougeres 2",
    "guerche de bretagne",
    "guichen",
    "janze",
    "liffre",
    "melesse",
    "montauban de bretagne",
    "montfort sur meu",
    "redon",
    "rennes 1",
    "rennes 2",
    "rennes 3",
    "rennes 4",
    "rennes 5",
    "rennes 6",
    "rheu",
    "saint malo 1",
    "saint malo 2",
    "vitre",
    "ardentes",
    "argenton sur creuse",
    "blanc",
    "buzancais",
    "chateauroux 1",
    "chateauroux 2",
    "chateauroux 3",
    "chatre",
    "issoudun",
    "levroux",
    "neuvy saint sepulchre",
    "saint gaultier",
    "valencay",
    "amboise",
    "ballan mire",
    "blere",
    "chateau renault",
    "chinon",
    "descartes",
    "joue les tours",
    "langeais",
    "loches",
    "montlouis sur loire",
    "monts",
    "saint cyr sur loire",
    "sainte maure de touraine",
    "saint pierre des corps",
    "tours 1",
    "tours 2",
    "tours 3",
    "tours 4",
    "vouvray",
    "bievre",
    "bourgoin jallieu",
    "chartreuse guiers",
    "charvieu chavagneux",
    "echirolles",
    "fontaine seyssinet",
    "fontaine vercors",
    "grand lemps",
    "grenoble 1",
    "grenoble 2",
    "grenoble 3",
    "grenoble 4",
    "haut gresivaudan",
    "isle d'abeau",
    "matheysine trieves",
    "meylan",
    "morestel",
    "moyen gresivaudan",
    "oisans romanche",
    "pont de claix",
    "roussillon",
    "saint martin d'heres",
    "sud gresivaudan",
    "tour du pin",
    "tullins",
    "verpilliere",
    "vienne 1",
    "vienne 2",
    "voiron",
    "arbois",
    "authume",
    "bletterans",
    "champagnole",
    "dole 1",
    "dole 2",
    "lons le saunier 1",
    "lons le saunier 2",
    "moirans en montagne",
    "mont sous vaudrey",
    "morez",
    "poligny",
    "saint amour",
    "saint claude",
    "saint laurent en grandvaux",
    "saint lupicin",
    "tavaux",
    "adour armagnac",
    "chalosse tursan",
    "cote d'argent",
    "coteau de chalosse",
    "dax 1",
    "dax 2",
    "grands lacs",
    "haute lande armagnac",
    "marensin sud",
    "mont de marsan 1",
    "mont de marsan 2",
    "orthe et arrigans",
    "pays morcenais tarusate",
    "pays tyrossais",
    "seignanx",
    "beauce",
    "blois 1",
    "blois 2",
    "blois 3",
    "chambord",
    "montoire sur le loir",
    "montrichard",
    "onzain",
    "perche",
    "romorantin lanthenay",
    "saint aignan",
    "selles sur cher",
    "sologne",
    "vendome",
    "vineuil",
    "andrezieux boutheon",
    "boen sur lignon",
    "charlieu",
    "coteau",
    "feurs",
    "firminy",
    "montbrison",
    "pilat",
    "renaison",
    "rive de gier",
    "roanne 1",
    "roanne 2",
    "saint chamond",
    "saint etienne 1",
    "saint etienne 2",
    "saint etienne 3",
    "saint etienne 4",
    "saint etienne 5",
    "saint etienne 6",
    "saint just saint rambert",
    "sorbiers",
    "aurec sur loire",
    "bas en basset",
    "boutieres",
    "brioude",
    "deux rivieres et vallees",
    "emblavez et meygal",
    "gorges de l'allier gevaudan",
    "mezenc",
    "monistrol sur loire",
    "pays de lafayette",
    "plateau du haut velay granitique",
    "puy en velay 1",
    "puy en velay 2",
    "puy en velay 3",
    "puy en velay 4",
    "saint paulien",
    "sainte florine",
    "velay volcanique",
    "yssingeaux",
    "ancenis",
    "baule escoublac",
    "blain",
    "carquefou",
    "chapelle sur erdre",
    "chateaubriant",
    "clisson",
    "guemene penfao",
    "guerande",
    "machecoul",
    "nantes 1",
    "nantes 2",
    "nantes 3",
    "nantes 4",
    "nantes 5",
    "nantes 6",
    "nantes 7",
    "nort sur erdre",
    "pontchateau",
    "pornic",
    "reze 1",
    "reze 2",
    "saint brevin les pins",
    "saint herblain 1",
    "saint herblain 2",
    "saint nazaire 1",
    "saint nazaire 2",
    "saint philbert de grand lieu",
    "saint sebastien sur loire",
    "vallet",
    "vertou",
    "beaugency",
    "chalette sur loing",
    "chateauneuf sur loire",
    "courtenay",
    "ferte saint aubin",
    "fleury les aubrais",
    "gien",
    "lorris",
    "malesherbes",
    "meung sur loire",
    "montargis",
    "olivet",
    "orleans 1",
    "orleans 2",
    "orleans 3",
    "orleans 4",
    "pithiviers",
    "saint jean de braye",
    "saint jean de la ruelle",
    "saint jean le blanc",
    "sully sur loire",
    "cahors 1",
    "cahors 2",
    "cahors 3",
    "causse et bouriane",
    "causse et vallees",
    "cere et segala",
    "figeac 1",
    "figeac 2",
    "gourdon",
    "gramat",
    "lacapelle marival",
    "luzech",
    "marches du sud quercy",
    "martel",
    "puy l'eveque",
    "saint cere",
    "souillac",
    "agen 1",
    "agen 2",
    "agen 3",
    "agen 4",
    "albret",
    "confluent",
    "coteaux de guyenne",
    "forets de gascogne",
    "fumelois",
    "haut agenais perigord",
    "lavardac",
    "livradais",
    "marmande 1",
    "marmande 2",
    "ouest agenais",
    "pays de serres",
    "sud est agenais",
    "tonneins",
    "val du dropt",
    "villeneuve sur lot 1",
    "villeneuve sur lot 2",
    "aumont aubrac",
    "canourgue",
    "chirac",
    "collet de deze",
    "florac",
    "grandrieu",
    "langogne",
    "marvejols",
    "mende 1",
    "mende 2",
    "saint alban sur limagnole",
    "saint chely d'apcher",
    "saint etienne du valdonnez",
    "angers 1",
    "angers 2",
    "angers 3",
    "angers 4",
    "angers 5",
    "angers 6",
    "angers 7",
    "beaufort en vallee",
    "beaupreau",
    "chalonnes sur loire",
    "chemille melay",
    "cholet 1",
    "cholet 2",
    "doue la fontaine",
    "longue jumelles",
    "pommeraye",
    "ponts de ce",
    "saint macaire en mauges",
    "saumur",
    "segre",
    "tierce",
    "agon coutainville",
    "avranches",
    "brehal",
    "bricquebec",
    "carentan",
    "cherbourg octeville 1",
    "cherbourg octeville 2",
    "cherbourg octeville 3",
    "conde sur vire",
    "coutances",
    "creances",
    "equeurdreville hainneville",
    "granville",
    "hague",
    "isigny le buat",
    "mortainais",
    "pieux",
    "pont hebert",
    "pontorson",
    "quettreville sur sienne",
    "saint hilaire du harcouet",
    "saint lo 1",
    "saint lo 2",
    "tourlaville",
    "valognes",
    "val de saire",
    "villedieu les poeles",
    "argonne suippe et vesle",
    "bourgogne",
    "chalons en champagne 1",
    "chalons en champagne 2",
    "chalons en champagne 3",
    "dormans paysages de champagne",
    "epernay 1",
    "epernay 2",
    "fismes montagne de reims",
    "mourmelon vesle et monts de champagne",
    "reims 1",
    "reims 2",
    "reims 3",
    "reims 4",
    "reims 5",
    "reims 6",
    "reims 7",
    "reims 8",
    "reims 9",
    "sermaize les bains",
    "sezanne brie et champagne",
    "vertus plaine champenoise",
    "vitry le francois champagne et der",
    "bologne",
    "bourbonne les bains",
    "chalindrey",
    "chateauvillain",
    "chaumont 1",
    "chaumont 2",
    "chaumont 3",
    "eurville bienville",
    "joinville",
    "langres",
    "nogent",
    "poissons",
    "saint dizier 1",
    "saint dizier 2",
    "saint dizier 3",
    "villegusien le lac",
    "wassy",
    "aze",
    "bonchamp les laval",
    "chateau gontier",
    "cosse le vivien",
    "ernee",
    "evron",
    "gorron",
    "huisserie",
    "lassay les chateaux",
    "laval 1",
    "laval 2",
    "laval 3",
    "loiron",
    "mayenne",
    "meslay du maine",
    "saint berthevin",
    "villaines la juhel",
    "baccarat",
    "entre seille et meurthe",
    "grand couronne",
    "jarny",
    "jarville la malgrange",
    "laxou",
    "longwy",
    "luneville 1",
    "luneville 2",
    "meine au saintois",
    "mont saint martin",
    "nancy 1",
    "nancy 2",
    "nancy 3",
    "neuves maisons",
    "nord toulois",
    "pays de briey",
    "pont a mousson",
    "saint max",
    "toul",
    "val de lorraine sud",
    "vanduvre les nancy",
    "villerupt",
    "ancerville",
    "bar le duc 1",
    "bar le duc 2",
    "belleville sur meuse",
    "bouligny",
    "clermont en argonne",
    "commercy",
    "dieue sur meuse",
    "etain",
    "ligny en barrois",
    "montmedy",
    "revigny sur ornain",
    "saint mihiel",
    "stenay",
    "vaucouleurs",
    "verdun 1",
    "verdun 2",
    "auray",
    "gourin",
    "grand champ",
    "guer",
    "guidel",
    "hennebont",
    "lanester",
    "lorient 1",
    "lorient 2",
    "moreac",
    "muzillac",
    "ploemeur",
    "ploermel",
    "pluvigner",
    "pontivy",
    "questembert",
    "quiberon",
    "sene",
    "vannes 1",
    "vannes 2",
    "vannes 3",
    "algrange",
    "bitche",
    "boulay moselle",
    "bouzonville",
    "coteaux de moselle",
    "fameck",
    "faulquemont",
    "forbach",
    "freyming merlebach",
    "hayange",
    "metz 1",
    "metz 2",
    "metz 3",
    "metzervisse",
    "montigny les metz",
    "pays messin",
    "phalsbourg",
    "rombas",
    "saint avold",
    "sarralbe",
    "sarrebourg",
    "sarreguemines",
    "saulnois",
    "sillon mosellan",
    "stiring wendel",
    "thionville",
    "yutz",
    "charite sur loire",
    "chateau chinon",
    "clamecy",
    "corbigny",
    "cosne cours sur loire",
    "decize",
    "fourchambault",
    "guerigny",
    "imphy",
    "luzy",
    "nevers 1",
    "nevers 2",
    "nevers 3",
    "nevers 4",
    "pouilly sur loire",
    "saint pierre le moutier",
    "varennes vauzelles",
    "aniche",
    "annullin",
    "anzin",
    "armentieres",
    "aulnoye aymeries",
    "aulnoy lez valenciennes",
    "avesnes sur helpe",
    "bailleul",
    "cambrai",
    "cateau cambresis",
    "caudry",
    "coudekerque branche",
    "croix",
    "denain",
    "douai",
    "dunkerque 1",
    "dunkerque 2",
    "faches thumesnil",
    "fourmies",
    "grande synthe",
    "hazebrouck",
    "lambersart",
    "lille 1",
    "lille 2",
    "lille 3",
    "lille 4",
    "lille 5",
    "lille 6",
    "marly",
    "maubeuge",
    "orchies",
    "roubaix 1",
    "roubaix 2",
    "saint amand les eaux",
    "sin le noble",
    "templeuve",
    "tourcoing 1",
    "tourcoing 2",
    "valenciennes",
    "villeneuve d'ascq",
    "wormhout",
    "beauvais 1",
    "beauvais 2",
    "chantilly",
    "chaumont en vexin",
    "clermont",
    "compiegne 1",
    "compiegne 2",
    "creil",
    "crepy en valois",
    "estrees saint denis",
    "grandvilliers",
    "meru",
    "montataire",
    "mouy",
    "nanteuil le haudouin",
    "nogent sur oise",
    "noyon",
    "pont sainte maxence",
    "saint just en chaussee",
    "senlis",
    "thourotte",
    "aigle",
    "alencon 1",
    "alencon 2",
    "argentan 1",
    "argentan 2",
    "athis de l'orne",
    "bagnoles de l'orne",
    "bretoncelles",
    "ceton",
    "damigny",
    "domfront",
    "ferte mace",
    "flers 1",
    "flers 2",
    "magny le desert",
    "mortagne au perche",
    "radon",
    "rai",
    "sees",
    "tourouvre",
    "vimoutiers",
    "aire sur la lys",
    "arras 1",
    "arras 2",
    "arras 3",
    "auchel",
    "auxi le chateau",
    "avesnes le comte",
    "avion",
    "bapaume",
    "berck",
    "bethune",
    "beuvry",
    "boulogne sur mer 1",
    "boulogne sur mer 2",
    "brebieres",
    "bruay la buissiere",
    "bully les mines",
    "calais 1",
    "calais 2",
    "calais 3",
    "carvin",
    "desvres",
    "douvrin",
    "etaples",
    "fruges",
    "harnes",
    "henin beaumont 1",
    "henin beaumont 2",
    "lens",
    "lievin",
    "lillers",
    "longuenesse",
    "lumbres",
    "marck",
    "nux les mines",
    "outreau",
    "saint omer",
    "saint pol sur ternoise",
    "wingles",
    "aigueperse",
    "ambert",
    "aubiere",
    "beaumont",
    "billom",
    "brassac les mines",
    "cebazat",
    "chamalieres",
    "chatel guyon",
    "clermont ferrand 1",
    "clermont ferrand 2",
    "clermont ferrand 3",
    "clermont ferrand 4",
    "clermont ferrand 5",
    "clermont ferrand 6",
    "cournon d'auvergne",
    "gerzat",
    "issoire",
    "lezoux",
    "maringues",
    "martres de veyre",
    "monts du livradois",
    "orcines",
    "pont du chateau",
    "riom",
    "saint eloy les mines",
    "saint georges de mons",
    "saint ours",
    "sancy",
    "thiers",
    "vic le comte",
    "anglet",
    "artix et pays de soubestre",
    "baigura et mondarrain",
    "bayonne 1",
    "bayonne 2",
    "bayonne 3",
    "biarritz",
    "billere et coteaux de jurancon",
    "cur de bearn",
    "hendaye cote basque sud",
    "lescar, gave et terres du pont long",
    "montagne basque",
    "nive adour",
    "oloron sainte marie 1",
    "oloron sainte marie 2",
    "orthez et terres des gaves et du sel",
    "ouzom, gave et rives du neez",
    "pau 1",
    "pau 2",
    "pau 3",
    "pau 4",
    "pays de bidache, amikuze et ostibarre",
    "pays de morlaas et du montaneres",
    "saint jean de luz",
    "terres des luys et coteaux du vic bilh",
    "ustaritz vallees de nive et nivelle",
    "vallees de l'ousse et du lagoin",
    "aureilhan",
    "borderes sur l'echez",
    "coteaux",
    "haute bigorre",
    "lourdes 1",
    "lourdes 2",
    "moyen adour",
    "neste, aure et louron",
    "ossun",
    "tarbes 1",
    "tarbes 2",
    "tarbes 3",
    "val d'adour rustan madiranais",
    "vallee de l'arros et des baises",
    "vallee de barousse",
    "vallee des gaves",
    "vic en bigorre",
    "aspres",
    "canigou",
    "cote sableuse",
    "cote salanquaise",
    "cote vermeille",
    "perpignan 1",
    "perpignan 2",
    "perpignan 3",
    "perpignan 4",
    "perpignan 5",
    "perpignan 6",
    "plaine d'illiberis",
    "pyrenees catalanes",
    "riberal",
    "vallee de l'agly",
    "vallee de la tet",
    "vallespir alberes",
    "bischwiller",
    "bouxwiller",
    "brumath",
    "erstein",
    "haguenau",
    "hnheim",
    "illkirch graffenstaden",
    "ingwiller",
    "lingolsheim",
    "molsheim",
    "mutzig",
    "obernai",
    "reichshoffen",
    "saverne",
    "schiltigheim",
    "selestat",
    "strasbourg 1",
    "strasbourg 2",
    "strasbourg 3",
    "strasbourg 4",
    "strasbourg 5",
    "strasbourg 6",
    "wissembourg",
    "altkirch",
    "brunstatt",
    "cernay",
    "colmar 1",
    "colmar 2",
    "ensisheim",
    "guebwiller",
    "kingersheim",
    "masevaux",
    "mulhouse 1",
    "mulhouse 2",
    "mulhouse 3",
    "rixheim",
    "saint louis",
    "sainte marie aux mines",
    "wintzenheim",
    "wittenheim",
    "anse",
    "arbresle",
    "belleville",
    "bois d'oingt",
    "brignais",
    "genas",
    "gleize",
    "mornant",
    "saint symphorien d'ozon",
    "tarare",
    "thizy les bourgs",
    "vaugneray",
    "villefranche sur saone",
    "dampierre sur salon",
    "gray",
    "hericourt 1",
    "hericourt 2",
    "jussey",
    "lure 1",
    "lure 2",
    "luxeuil les bains",
    "marnay",
    "melisey",
    "port sur saone",
    "rioz",
    "saint loup sur semouse",
    "scey sur saone et saint albin",
    "vesoul 1",
    "vesoul 2",
    "villersexel",
    "autun 1",
    "autun 2",
    "blanzy",
    "chagny",
    "chalon sur saone 1",
    "chalon sur saone 2",
    "chalon sur saone 3",
    "chapelle de guinchay",
    "charolles",
    "chauffailles",
    "cluny",
    "creusot 1",
    "creusot 2",
    "cuiseaux",
    "digoin",
    "gergy",
    "givry",
    "gueugnon",
    "hurigny",
    "louhans",
    "macon 1",
    "macon 2",
    "montceau les mines",
    "ouroux sur saone",
    "paray le monial",
    "pierre de bresse",
    "saint remy",
    "saint vallier",
    "tournus",
    "bonnetable",
    "change",
    "chateau du loir",
    "ecommoy",
    "ferte bernard",
    "fleche",
    "loue",
    "lude",
    "mamers",
    "mans 1",
    "mans 2",
    "mans 3",
    "mans 4",
    "mans 5",
    "mans 6",
    "mans 7",
    "sable sur sarthe",
    "saint calais",
    "savigne l'eveque",
    "sille le guillaume",
    "suze sur sarthe",
    "aix les bains 1",
    "aix les bains 2",
    "albertville 1",
    "albertville 2",
    "bourg saint maurice",
    "bugey savoyard",
    "chambery 1",
    "chambery 2",
    "chambery 3",
    "modane",
    "montmelian",
    "motte servolex",
    "moutiers",
    "pont de beauvoisin",
    "ravoire",
    "saint alban leysse",
    "saint jean de maurienne",
    "saint pierre d'albigny",
    "ugine",
    "annecy 1",
    "annecy 2",
    "annecy le vieux",
    "annemasse",
    "bonneville",
    "cluses",
    "evian les bains",
    "faverges",
    "gaillard",
    "mont blanc",
    "roche sur foron",
    "rumilly",
    "saint julien en genevois",
    "sallanches",
    "sciez",
    "seynod",
    "thonon les bains",
    "barentin",
    "bois guillaume",
    "bolbec",
    "canteleu",
    "caudebec les elbeuf",
    "darnetal",
    "dieppe 1",
    "dieppe 2",
    "elbeuf",
    "eu",
    "fecamp",
    "gournay en bray",
    "grand quevilly",
    "havre 1",
    "havre 2",
    "havre 3",
    "havre 4",
    "havre 5",
    "havre 6",
    "luneray",
    "mesnil esnard",
    "mont saint aignan",
    "neufchatel en bray",
    "notre dame de bondeville",
    "notre dame de gravenchon",
    "octeville sur mer",
    "petit quevilly",
    "rouen 1",
    "rouen 2",
    "rouen 3",
    "saint etienne du rouvray",
    "saint romain de colbosc",
    "saint valery en caux",
    "sotteville les rouen",
    "yvetot",
    "champs sur marne",
    "chelles",
    "claye souilly",
    "combs la ville",
    "coulommiers",
    "ferte sous jouarre",
    "fontainebleau",
    "fontenay tresigny",
    "lagny sur marne",
    "meaux",
    "melun",
    "mitry mory",
    "montereau fault yonne",
    "nangis",
    "nemours",
    "ozoir la ferriere",
    "pontault combault",
    "provins",
    "saint fargeau ponthierry",
    "savigny le temple",
    "serris",
    "torcy",
    "villeparisis",
    "aubergenville",
    "bonnieres sur seine",
    "chatou",
    "chesnay",
    "conflans sainte honorine",
    "houilles",
    "limay",
    "mantes la jolie",
    "maurepas",
    "montigny le bretonneux",
    "mureaux",
    "plaisir",
    "poissy",
    "rambouillet",
    "saint cyr l'ecole",
    "saint germain en laye",
    "sartrouville",
    "trappes",
    "verneuil sur seine",
    "versailles 1",
    "versailles 2",
    "autize egray",
    "bressuire",
    "celles sur belle",
    "cerizay",
    "frontenay rohan rohan",
    "gatine",
    "mauleon",
    "melle",
    "mignon et boutonne",
    "niort 1",
    "niort 2",
    "niort 3",
    "parthenay",
    "plaine niortaise",
    "saint maixent l'ecole",
    "thouars",
    "val de thouet",
    "abbeville 1",
    "abbeville 2",
    "ailly sur noye",
    "ailly sur somme",
    "albert",
    "amiens 1",
    "amiens 2",
    "amiens 3",
    "amiens 4",
    "amiens 5",
    "amiens 6",
    "amiens 7",
    "corbie",
    "doullens",
    "flixecourt",
    "friville escarbotin",
    "gamaches",
    "ham",
    "moreuil",
    "peronne",
    "poix de picardie",
    "roye",
    "rue",
    "albi 1",
    "albi 2",
    "albi 3",
    "albi 4",
    "carmaux 1 le segala",
    "carmaux 2 vallee du cerou",
    "castres 1",
    "castres 2",
    "castres 3",
    "deux rives",
    "gaillac",
    "graulhet",
    "haut dadou",
    "hautes terres d'oc",
    "lavaur cocagne",
    "mazamet 1",
    "mazamet 2 vallee du thore",
    "montagne noire",
    "pastel",
    "plaine de l'agout",
    "portes du tarn",
    "saint juery",
    "vignobles et bastides",
    "aveyron lere",
    "beaumont de lomagne",
    "castelsarrasin",
    "garonne lomagne brulhois",
    "moissac",
    "montauban 1",
    "montauban 2",
    "montauban 3",
    "montech",
    "pays de serres sud quercy",
    "quercy aveyron",
    "quercy rouergue",
    "tarn tescou quercy vert",
    "valence",
    "verdun sur garonne",
    "brignoles",
    "crau",
    "draguignan",
    "flayosc",
    "frejus",
    "garde",
    "gareoult",
    "hyeres",
    "luc",
    "ollioules",
    "roquebrune sur argens",
    "saint cyr sur mer",
    "saint maximin la sainte baume",
    "saint raphael",
    "sainte maxime",
    "seyne sur mer 1",
    "seyne sur mer 2",
    "sollies pont",
    "toulon 1",
    "toulon 2",
    "toulon 3",
    "toulon 4",
    "vidauban",
    "apt",
    "avignon 1",
    "avignon 2",
    "avignon 3",
    "bollene",
    "carpentras",
    "cavaillon",
    "cheval blanc",
    "isle sur la sorgue",
    "monteux",
    "orange",
    "pernes les fontaines",
    "pertuis",
    "pontet",
    "sorgues",
    "vaison la romaine",
    "valreas",
    "aizenay",
    "challans",
    "chantonnay",
    "chataigneraie",
    "fontenay le comte",
    "herbiers",
    "ile d'yeu",
    "lucon",
    "mareuil sur lay dissais",
    "montaigu",
    "mortagne sur sevre",
    "roche sur yon 1",
    "roche sur yon 2",
    "sables d'olonne",
    "saint hilaire de riez",
    "saint jean de monts",
    "talmont saint hilaire",
    "chasseneuil du poitou",
    "chatellerault 1",
    "chatellerault 2",
    "chatellerault 3",
    "chauvigny",
    "civray",
    "jaunay clan",
    "loudun",
    "lusignan",
    "lussac les chateaux",
    "migne auxances",
    "montmorillon",
    "poitiers 1",
    "poitiers 2",
    "poitiers 3",
    "poitiers 4",
    "poitiers 5",
    "vivonne",
    "vouneuil sous biard",
    "aixe sur vienne",
    "ambazac",
    "bellac",
    "chateauponsac",
    "condat sur vienne",
    "couzeix",
    "eymoutiers",
    "limoges 1",
    "limoges 2",
    "limoges 3",
    "limoges 4",
    "limoges 5",
    "limoges 6",
    "limoges 7",
    "limoges 8",
    "limoges 9",
    "panazol",
    "rochechouart",
    "saint junien",
    "saint leonard de noblat",
    "saint yrieix la perche",
    "bresse",
    "bruyeres",
    "charmes",
    "darney",
    "epinal 1",
    "epinal 2",
    "gerardmer",
    "golbey",
    "mirecourt",
    "neufchateau",
    "raon l'etape",
    "remiremont",
    "saint die des vosges 1",
    "saint die des vosges 2",
    "thillot",
    "val d'ajol",
    "vittel",
    "auxerre 1",
    "auxerre 2",
    "auxerre 3",
    "auxerre 4",
    "avallon",
    "brienon sur armancon",
    "chablis",
    "charny",
    "cur de puisaye",
    "gatinais en bourgogne",
    "joigny",
    "joux la ville",
    "migennes",
    "pont sur yonne",
    "saint florentin",
    "sens 1",
    "sens 2",
    "thorigny sur oreuse",
    "tonnerrois",
    "villeneuve sur yonne",
    "vincelles",
    "bavilliers",
    "belfort 1",
    "belfort 2",
    "belfort 3",
    "chatenois les forges",
    "delle",
    "giromagny",
    "grandvillars",
    "valdoie",
    "arpajon",
    "athis mons",
    "bretigny sur orge",
    "corbeil essonnes",
    "dourdan",
    "draveil",
    "epinay sous senart",
    "etampes",
    "evry",
    "gif sur yvette",
    "longjumeau",
    "massy",
    "mennecy",
    "palaiseau",
    "ris orangis",
    "sainte genevieve des bois",
    "savigny sur orge",
    "ulis",
    "vigneux sur seine",
    "viry chatillon",
    "yerres",
    "antony",
    "asnieres sur seine",
    "bagneux",
    "boulogne billancourt 1",
    "boulogne billancourt 2",
    "chatenay malabry",
    "chatillon",
    "clamart",
    "clichy",
    "colombes 1",
    "colombes 2",
    "courbevoie 1",
    "courbevoie 2",
    "gennevilliers",
    "issy les moulineaux",
    "levallois perret",
    "meudon",
    "montrouge",
    "nanterre 1",
    "nanterre 2",
    "neuilly sur seine",
    "rueil malmaison",
    "saint cloud",
    "aubervilliers",
    "aulnay sous bois",
    "bagnolet",
    "blanc mesnil",
    "bobigny",
    "bondy",
    "courneuve",
    "drancy",
    "epinay sur seine",
    "gagny",
    "livry gargan",
    "montreuil 1",
    "montreuil 2",
    "noisy le grand",
    "pantin",
    "saint denis 1",
    "saint denis 2",
    "saint ouen",
    "sevran",
    "tremblay en france",
    "villemomble",
    "alfortville",
    "cachan",
    "champigny sur marne 1",
    "champigny sur marne 2",
    "charenton le pont",
    "choisy le roi",
    "creteil 1",
    "creteil 2",
    "fontenay sous bois",
    "hay les roses",
    "ivry sur seine",
    "kremlin bicetre",
    "maisons alfort",
    "nogent sur marne",
    "orly",
    "plateau briard",
    "saint maur des fosses 1",
    "saint maur des fosses 2",
    "thiais",
    "villejuif",
    "villeneuve saint georges",
    "villiers sur marne",
    "vincennes",
    "vitry sur seine 1",
    "vitry sur seine 2",
    "argenteuil 1",
    "argenteuil 2",
    "argenteuil 3",
    "cergy 1",
    "cergy 2",
    "deuil la barre",
    "domont",
    "ermont",
    "fosses",
    "franconville",
    "garges les gonesse",
    "goussainville",
    "herblay",
    "isle adam",
    "montmorency",
    "pontoise",
    "saint ouen l'aumone",
    "sarcelles",
    "taverny",
    "vaureal",
    "villiers le bel",
    "abymes 1",
    "abymes 2",
    "abymes 3",
    "baie mahault 1",
    "baie mahault 2",
    "basse terre",
    "capesterre belle eau",
    "gosier",
    "lamentin",
    "marie galante",
    "moule",
    "morne a l'eau",
    "petit bourg",
    "petit canal",
    "pointe a pitre",
    "saint francois",
    "sainte anne",
    "sainte rose 1",
    "sainte rose 2",
    "trois rivieres",
    "vieux habitants",
    "etang sale",
    "port",
    "possession",
    "saint andre 1",
    "saint andre 2",
    "saint andre 3",
    "saint benoit 1",
    "saint benoit 2",
    "saint denis 1",
    "saint denis 2",
    "saint denis 3",
    "saint denis 4",
    "saint joseph",
    "saint leu",
    "saint louis 1",
    "saint louis 2",
    "saint paul 1",
    "saint paul 2",
    "saint paul 3",
    "saint pierre 1",
    "saint pierre 2",
    "saint pierre 3",
    "sainte marie",
    "tampon 1",
    "tampon 2",
    "bandraboua",
    "boueni",
    "dembeni",
    "dzaoudzi",
    "koungou",
    "mamoudzou 1",
    "mamoudzou 2",
    "mamoudzou 3",
    "mtsamboro",
    "ouangani",
    "pamandzi",
    "sada",
    "tsingoni",
}
