PAYS_COG_2024 = frozenset(
    {
        "France",
        "Danemark",
        "Islande",
        "Norvège",
        "Suède",
        "Finlande",
        "Estonie",
        "Lettonie",
        "Lituanie",
        "Allemagne",
        "Autriche",
        "Bulgarie",
        "Hongrie",
        "Liechtenstein",
        "Roumanie",
        "Tchéquie",
        "Slovaquie",
        "Bosnie-Herzégovine",
        "Croatie",
        "Monténégro",
        "Serbie",
        "Pologne",
        "Russie",
        "Albanie",
        "Grèce",
        "Italie",
        "Saint-Marin",
        "Vatican",
        "Andorre",
        "Belgique",
        "Royaume-Uni",
        "Territoires britanniques en Méditerranée",
        "Espagne",
        "Pays-Bas",
        "Irlande",
        "Luxembourg",
        "Monaco",
        "Portugal",
        "Suisse",
        "Malte",
        "Slovénie",
        "Biélorussie",
        "Moldavie",
        "Ukraine",
        "Macédoine du Nord",
        "Kosovo",
        "Féroé",
        "Territoires norvégiens en Atlantique Nord",
        "Åland",
        "Dépendances de la Couronne britannique",
        "Arabie saoudite",
        "Irak",
        "Iran",
        "Liban",
        "Syrie",
        "Israël",
        "Turquie",
        "Afghanistan",
        "Pakistan",
        "Bhoutan",
        "Népal",
        "Chine",
        "Japon",
        "Thaïlande",
        "Philippines",
        "Jordanie",
        "Inde",
        "Birmanie",
        "Brunei",
        "Singapour",
        "Malaisie",
        "Maldives",
        "Hong Kong",
        "Indonésie",
        "Macao",
        "Cambodge",
        "Sri Lanka",
        "Taïwan",
        "Corée du Nord",
        "Corée du Sud",
        "Koweït",
        "Laos",
        "Mongolie",
        "Vietnam",
        "Bangladesh",
        "Émirats arabes unis",
        "Qatar",
        "Bahreïn",
        "Oman",
        "Yémen",
        "Arménie",
        "Azerbaïdjan",
        "Chypre",
        "Géorgie",
        "Kazakhstan",
        "Kirghizstan",
        "Ouzbékistan",
        "Tadjikistan",
        "Turkménistan",
        "Palestine",
        "Timor oriental",
        "Territoires australiens de l’océan Indien",
        "Égypte",
        "Libéria",
        "Afrique du Sud",
        "Gambie",
        "Territoires britanniques de l’océan Atlantique",
        "Chagos",
        "Tanzanie",
        "Zimbabwe",
        "Namibie",
        "République démocratique du Congo",
        "Territoires espagnols en Afrique du Nord",
        "Guinée équatoriale",
        "Éthiopie",
        "Libye",
        "Érythrée",
        "Somalie",
        "Territoires portugais de l’océan Atlantique",
        "Burundi",
        "Cameroun",
        "Centrafrique",
        "Congo",
        "Côte d’Ivoire",
        "Bénin",
        "Gabon",
        "Ghana",
        "Guinée",
        "Burkina",
        "Kenya",
        "Madagascar",
        "Malawi",
        "Mali",
        "Mauritanie",
        "Niger",
        "Nigéria",
        "Ouganda",
        "Rwanda",
        "Sénégal",
        "Sierra Leone",
        "Soudan",
        "Tchad",
        "Togo",
        "Zambie",
        "Botswana",
        "Lesotho",
        "Soudan du Sud",
        "Maroc",
        "Tunisie",
        "Algérie",
        "Terres australes norvégiennes",
        "Sahara occidental",
        "Maurice",
        "Swaziland",
        "Guinée-Bissao",
        "Mozambique",
        "Sao Tomé-et-Principe",
        "Angola",
        "Cap-Vert",
        "Comores",
        "Seychelles",
        "Djibouti",
        "Canada",
        "États-Unis",
        "Mexique",
        "Costa Rica",
        "Cuba",
        "République dominicaine",
        "Guatemala",
        "Haïti",
        "Honduras",
        "Nicaragua",
        "Panama",
        "Salvador",
        "Argentine",
        "Brésil",
        "Chili",
        "Bolivie",
        "Colombie",
        "Équateur",
        "Paraguay",
        "Pérou",
        "Uruguay",
        "Vénézuéla",
        "Territoires britanniques dans les Antilles et Bermudes",
        "Jamaïque",
        "Territoires britanniques dans l’océan Atlantique Sud",
        "Guyana",
        "Bélize",
        "Groenland",
        "Aruba",
        "Territoires des États-Unis en Amérique",
        "Trinité-et-Tobago",
        "Barbade",
        "Grenade",
        "Bahamas",
        "Suriname",
        "Dominique",
        "Sainte-Lucie",
        "Saint-Vincent-et-les-Grenadines",
        "Antigua-et-Barbuda",
        "Saint-Christophe-et-Niévès",
        "Bonaire, Saint-Eustache, Saba",
        "Curaçao",
        "Saint-Martin (partie néerlandaise)",
        "Antarctique argentin",
        "Territoire chilien de l'Antarctique",
        "Australie",
        "Nouvelle-Zélande",
        "Pitcairn",
        "Territoires des États-Unis en Océanie",
        "Samoa",
        "Nauru",
        "Fidji",
        "Tonga",
        "Papouasie-Nouvelle-Guinée",
        "Tuvalu",
        "Salomon",
        "Kiribati",
        "Vanuatu",
        "Marshall",
        "Micronésie",
        "Palaos",
        "Territoires de la Nouvelle-Zélande",
        "Cook",
        "Niue",
        "Territoires de l’Australie en Océanie",
        "Antarctique",
    }
)
