PAYS_SET_COG_2023 = {
    "DANEMARK",
    "FEROE (ILES)",
    "ISLANDE",
    "NORVEGE",
    "SVALBARD et ILE JAN MAYEN",
    "BOUVET (ILE)",
    "SUEDE",
    "FINLANDE",
    "ESTONIE",
    "LETTONIE",
    "LITUANIE",
    "ALLEMAGNE",
    "AUTRICHE",
    "BULGARIE",
    "HONGRIE",
    "LIECHTENSTEIN",
    "ROUMANIE",
    "TCHECOSLOVAQUIE",
    "TCHEQUIE",
    "SLOVAQUIE",
    "BOSNIE-HERZEGOVINE",
    "CROATIE",
    "MONTENEGRO",
    "SERBIE",
    "POLOGNE",
    "RUSSIE",
    "TURQUIE D'EUROPE",
    "ALBANIE",
    "GRECE",
    "ITALIE",
    "SAINT-MARIN",
    "VATICAN, ou SAINT-SIEGE",
    "ANDORRE",
    "BELGIQUE",
    "ROYAUME-UNI",
    "JERSEY",
    "MAN (ILE)",
    "GUERNESEY",
    "GIBRALTAR",
    "ESPAGNE",
    "PAYS-BAS",
    "ARUBA",
    "IRLANDE, ou EIRE",
    "LUXEMBOURG",
    "MONACO",
    "PORTUGAL",
    "SUISSE",
    "REPUBLIQUE DEMOCRATIQUE ALLEMANDE",
    "REPUBLIQUE FEDERALE D'ALLEMAGNE",
    "MALTE",
    "SLOVENIE",
    "BIELORUSSIE",
    "MOLDAVIE",
    "UKRAINE",
    "MACEDOINE DU NORD",
    "KOSOVO",
    "ARABIE SAOUDITE",
    "YEMEN (REPUBLIQUE ARABE DU)",
    "IRAQ",
    "IRAN",
    "LIBAN",
    "SYRIE",
    "ISRAEL",
    "TURQUIE",
    "SIBERIE",
    "TURKESTAN RUSSE",
    "KAMTCHATKA",
    "AFGHANISTAN",
    "PAKISTAN",
    "BHOUTAN",
    "NEPAL",
    "CHINE",
    "JAPON",
    "MANDCHOURIE",
    "THAILANDE",
    "PHILIPPINES",
    "POSSESSIONS BRITANNIQUES AU PROCHE-ORIENT",
    "JORDANIE",
    "INDE",
    "GOA",
    "BIRMANIE",
    "BRUNEI",
    "SINGAPOUR",
    "MALAISIE",
    "ETATS MALAIS NON FEDERES",
    "MALDIVES",
    "HONG-KONG",
    "INDONESIE",
    "MACAO",
    "YEMEN DEMOCRATIQUE",
    "CAMBODGE",
    "SRI LANKA",
    "TAIWAN",
    "COREE",
    "COREE (REPUBLIQUE POPULAIRE DEMOCRATIQUE DE)",
    "COREE (REPUBLIQUE DE)",
    "KOWEIT",
    "LAOS",
    "MONGOLIE",
    "VIET NAM",
    "VIET NAM DU NORD",
    "VIET NAM DU SUD",
    "BANGLADESH",
    "EMIRATS ARABES UNIS",
    "QATAR",
    "BAHREIN",
    "OMAN",
    "YEMEN",
    "ARMENIE",
    "AZERBAIDJAN",
    "CHYPRE",
    "GEORGIE",
    "KAZAKHSTAN",
    "KIRGHIZISTAN",
    "OUZBEKISTAN",
    "TADJIKISTAN",
    "TURKMENISTAN",
    "PALESTINE (Etat de)",
    "TIMOR ORIENTAL",
    "EGYPTE",
    "LIBERIA",
    "AFRIQUE DU SUD",
    "GAMBIE",
    "CAMEROUN ET TOGO",
    "SAINTE HELENE, ASCENSION ET TRISTAN DA CUNHA",
    "SOUDAN ANGLO-EGYPTIEN, KENYA, OUGANDA",
    "ZANZIBAR",
    "OCEAN INDIEN (TERRITOIRE BRITANNIQUE DE L')",
    "TANZANIE",
    "ZIMBABWE",
    "NAMIBIE",
    "CONGO (REPUBLIQUE DEMOCRATIQUE)",
    "PROVINCES ESPAGNOLES D'AFRIQUE",
    "PRESIDES",
    "CANARIES (ILES)",
    "GUINEE EQUATORIALE",
    "ETHIOPIE",
    "LIBYE",
    "ERYTHREE",
    "SOMALIE",
    "ACORES, MADERE",
    "ILES PORTUGAISES DE L'OCEAN INDIEN",
    "BURUNDI",
    "CAMEROUN",
    "CENTRAFRICAINE (REPUBLIQUE)",
    "CONGO",
    "TANGER",
    "COTE D'IVOIRE",
    "BENIN",
    "GABON",
    "GHANA",
    "GUINEE",
    "BURKINA",
    "KENYA",
    "MADAGASCAR",
    "MALAWI",
    "MALI",
    "MAURITANIE",
    "NIGER",
    "NIGERIA",
    "OUGANDA",
    "RWANDA",
    "SENEGAL",
    "SIERRA LEONE",
    "SOUDAN",
    "TCHAD",
    "TOGO",
    "ZAMBIE",
    "BOTSWANA",
    "LESOTHO",
    "SOUDAN DU SUD",
    "MAROC",
    "TUNISIE",
    "ALGERIE",
    "SAHARA OCCIDENTAL",
    "MAURICE",
    "ESWATINI",
    "GUINEE-BISSAU",
    "MOZAMBIQUE",
    "SAO TOME-ET-PRINCIPE",
    "ANGOLA",
    "CAP-VERT",
    "COMORES",
    "SEYCHELLES",
    "DJIBOUTI",
    "CANADA",
    "TERRE-NEUVE",
    "LABRADOR",
    "ETATS-UNIS",
    "ALASKA",
    "MEXIQUE",
    "COSTA RICA",
    "CUBA",
    "DOMINICAINE (REPUBLIQUE)",
    "GUATEMALA",
    "HAITI",
    "HONDURAS",
    "NICARAGUA",
    "PANAMA",
    "EL SALVADOR",
    "ARGENTINE",
    "BRESIL",
    "CHILI",
    "BOLIVIE",
    "COLOMBIE",
    "EQUATEUR",
    "PARAGUAY",
    "PEROU",
    "URUGUAY",
    "VENEZUELA",
    "TERRITOIRES DU ROYAUME-UNI AUX ANTILLES",
    "VIERGES BRITANNIQUES (ILES)",
    "TURKS ET CAIQUES (ILES)",
    "MONTSERRAT",
    "CAIMANES (ILES)",
    "BERMUDES",
    "ANGUILLA",
    "JAMAIQUE",
    "TERR. DU ROYAUME-UNI DANS L'ATLANTIQUE SUD",
    "GEORGIE DU SUD ET LES ILES SANDWICH DU SUD",
    "MALOUINES, OU FALKLAND (ILES)",
    "GUYANA",
    "BELIZE",
    "GROENLAND",
    "ANTILLES NEERLANDAISES",
    "TERR. DES ETATS-UNIS D'AMERIQUE EN AMERIQUE",
    "VIERGES DES ETATS-UNIS (ILES)",
    "PORTO RICO",
    "TRINITE-ET-TOBAGO",
    "BARBADE",
    "GRENADE",
    "BAHAMAS",
    "SURINAME",
    "DOMINIQUE",
    "SAINTE-LUCIE",
    "SAINT-VINCENT-ET-LES GRENADINES",
    "ANTIGUA-ET-BARBUDA",
    "SAINT-CHRISTOPHE-ET-NIEVES",
    "BONAIRE, SAINT EUSTACHE ET SABA",
    "CURAÇAO",
    "SAINT-MARTIN (PARTIE NEERLANDAISE)",
    "AUSTRALIE",
    "NORFOLK (ILE)",
    "HEARD ET MACDONALD (ILES)",
    "CHRISTMAS (ILE)",
    "COCOS ou KEELING (ILES)",
    "NOUVELLE-ZELANDE",
    "TOKELAU",
    "NIUE",
    "COOK (ILES)",
    "PITCAIRN (ILE)",
    "HAWAII (ILES)",
    "TERR. DES ETATS-UNIS D'AMERIQUE EN OCEANIE",
    "MARIANNES DU NORD (ILES)",
    "GUAM",
    "SAMOA AMERICAINES",
    "SAMOA OCCIDENTALES",
    "NAURU",
    "FIDJI",
    "TONGA",
    "PAPOUASIE-NOUVELLE-GUINEE",
    "TUVALU",
    "SALOMON (ILES)",
    "KIRIBATI",
    "VANUATU",
    "MARSHALL (ILES)",
    "MICRONESIE (ETATS FEDERES DE)",
    "PALAOS (ILES)",
    "FRANCE",
    "CLIPPERTON (ILE)",
    "MAYOTTE",
    "WALLIS-ET-FUTUNA",
    "TERRES AUSTRALES FRANCAISES",
    "LA REUNION",
    "SAINT-PIERRE-ET-MIQUELON",
    "POLYNESIE FRANCAISE",
    "NOUVELLE-CALEDONIE",
    "MARTINIQUE",
    "SAINT-MARTIN",
    "GUADELOUPE",
    "GUYANE",
    "SAINT-BARTHELEMY",
}

PAYS_SET_COG_2024 = {
    "France",
    "Danemark",
    "Islande",
    "Norvège",
    "Suède",
    "Finlande",
    "Estonie",
    "Lettonie",
    "Lituanie",
    "Allemagne",
    "Autriche",
    "Bulgarie",
    "Hongrie",
    "Liechtenstein",
    "Roumanie",
    "Tchéquie",
    "Slovaquie",
    "Bosnie-Herzégovine",
    "Croatie",
    "Monténégro",
    "Serbie",
    "Pologne",
    "Russie",
    "Albanie",
    "Grèce",
    "Italie",
    "Saint-Marin",
    "Vatican",
    "Andorre",
    "Belgique",
    "Royaume-Uni",
    "Territoires britanniques en Méditerranée",
    "Espagne",
    "Pays-Bas",
    "Irlande",
    "Luxembourg",
    "Monaco",
    "Portugal",
    "Suisse",
    "Malte",
    "Slovénie",
    "Biélorussie",
    "Moldavie",
    "Ukraine",
    "Macédoine du Nord",
    "Kosovo",
    "Féroé",
    "Territoires norvégiens en Atlantique Nord",
    "Åland",
    "Dépendances de la Couronne britannique",
    "Arabie saoudite",
    "Irak",
    "Iran",
    "Liban",
    "Syrie",
    "Israël",
    "Turquie",
    "Afghanistan",
    "Pakistan",
    "Bhoutan",
    "Népal",
    "Chine",
    "Japon",
    "Thaïlande",
    "Philippines",
    "Jordanie",
    "Inde",
    "Birmanie",
    "Brunei",
    "Singapour",
    "Malaisie",
    "Maldives",
    "Hong Kong",
    "Indonésie",
    "Macao",
    "Cambodge",
    "Sri Lanka",
    "Taïwan",
    "Corée du Nord",
    "Corée du Sud",
    "Koweït",
    "Laos",
    "Mongolie",
    "Vietnam",
    "Bangladesh",
    "Émirats arabes unis",
    "Qatar",
    "Bahreïn",
    "Oman",
    "Yémen",
    "Arménie",
    "Azerbaïdjan",
    "Chypre",
    "Géorgie",
    "Kazakhstan",
    "Kirghizstan",
    "Ouzbékistan",
    "Tadjikistan",
    "Turkménistan",
    "Palestine",
    "Timor oriental",
    "Territoires australiens de l’océan Indien",
    "Égypte",
    "Libéria",
    "Afrique du Sud",
    "Gambie",
    "Territoires britanniques de l’océan Atlantique",
    "Chagos",
    "Tanzanie",
    "Zimbabwe",
    "Namibie",
    "République démocratique du Congo",
    "Territoires espagnols en Afrique du Nord",
    "Guinée équatoriale",
    "Éthiopie",
    "Libye",
    "Érythrée",
    "Somalie",
    "Territoires portugais de l’océan Atlantique",
    "Burundi",
    "Cameroun",
    "Centrafrique",
    "Congo",
    "Côte d’Ivoire",
    "Bénin",
    "Gabon",
    "Ghana",
    "Guinée",
    "Burkina",
    "Kenya",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritanie",
    "Niger",
    "Nigéria",
    "Ouganda",
    "Rwanda",
    "Sénégal",
    "Sierra Leone",
    "Soudan",
    "Tchad",
    "Togo",
    "Zambie",
    "Botswana",
    "Lesotho",
    "Soudan du Sud",
    "Maroc",
    "Tunisie",
    "Algérie",
    "Terres australes norvégiennes",
    "Sahara occidental",
    "Maurice",
    "Swaziland",
    "Guinée-Bissao",
    "Mozambique",
    "Sao Tomé-et-Principe",
    "Angola",
    "Cap-Vert",
    "Comores",
    "Seychelles",
    "Djibouti",
    "Canada",
    "États-Unis",
    "Mexique",
    "Costa Rica",
    "Cuba",
    "République dominicaine",
    "Guatemala",
    "Haïti",
    "Honduras",
    "Nicaragua",
    "Panama",
    "Salvador",
    "Argentine",
    "Brésil",
    "Chili",
    "Bolivie",
    "Colombie",
    "Équateur",
    "Paraguay",
    "Pérou",
    "Uruguay",
    "Vénézuéla",
    "Territoires britanniques dans les Antilles et Bermudes",
    "Jamaïque",
    "Territoires britanniques dans l’océan Atlantique Sud",
    "Guyana",
    "Bélize",
    "Groenland",
    "Aruba",
    "Territoires des États-Unis en Amérique",
    "Trinité-et-Tobago",
    "Barbade",
    "Grenade",
    "Bahamas",
    "Suriname",
    "Dominique",
    "Sainte-Lucie",
    "Saint-Vincent-et-les-Grenadines",
    "Antigua-et-Barbuda",
    "Saint-Christophe-et-Niévès",
    "Bonaire, Saint-Eustache, Saba",
    "Curaçao",
    "Saint-Martin (partie néerlandaise)",
    "Antarctique argentin",
    "Territoire chilien de l'Antarctique",
    "Australie",
    "Nouvelle-Zélande",
    "Pitcairn",
    "Territoires des États-Unis en Océanie",
    "Samoa",
    "Nauru",
    "Fidji",
    "Tonga",
    "Papouasie-Nouvelle-Guinée",
    "Tuvalu",
    "Salomon",
    "Kiribati",
    "Vanuatu",
    "Marshall",
    "Micronésie",
    "Palaos",
    "Territoires de la Nouvelle-Zélande",
    "Cook",
    "Niue",
    "Territoires de l’Australie en Océanie",
    "Antarctique",
}
