REGION_SET = {
    "Guadeloupe",
    "Martinique",
    "Guyane",
    "La Réunion",
    "Mayotte",
    "Île-de-France",
    "Centre-Val de Loire",
    "Bourgogne-Franche-Comté",
    "Normandie",
    "Hauts-de-France",
    "Grand Est",
    "Pays de la Loire",
    "Bretagne",
    "Nouvelle-Aquitaine",
    "Occitanie",
    "Auvergne-Rhône-Alpes",
    "Provence-Alpes-Côte d'Azur",
    "Corse",
}

LENIENT_REGION_SET = {
    "alsace",
    "aquitaine",
    "ara",
    "aura",
    "auvergne",
    "auvergne et rhone alpes",
    "auvergne rhone alpes",
    "basse normandie",
    "bfc",
    "bourgogne",
    "bourgogne et franche comte",
    "bourgogne franche comte",
    "bretagne",
    "centre",
    "centre val de loire",
    "champagne ardenne",
    "corse",
    "franche comte",
    "ge" "nouvelle aquitaine",
    "grand est",
    "guadeloupe",
    "guyane",
    "haute normandie",
    "hauts de france",
    "hdf",
    "ile de france",
    "languedoc roussillon",
    "la reunion",
    "la reunion",
    "limousin",
    "lorraine",
    "martinique",
    "mayotte",
    "midi pyrenees",
    "nord pas de calais",
    "normandie",
    "npdc",
    "occitanie",
    "paca",
    "pays de la loire",
    "picardie",
    "poitou charentes",
    "provence alpes cote d azur",
    "reunion",
    "rhone alpes",
}
