name: Pull Request Review & Merge

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: install poetry
        run: pip install poetry==1.6

      - name: install dependencies
        run: poetry install --with linting

      - name: linting
        run: make lint
  
  build:
    
  publish:



Publish on PyPI:
  stage: deploy-validata-table-package
  # To use private auto-hosted runner
  tags:
    - validata-table
  image: python:3.9-bullseye
  only:
    - tags
  before_script:
    - apt update -y && apt install -y rustc cargo # for "opening-hours" extension
    - pip install poetry
    - poetry build
    - pip install twine
  variables:
    TWINE_USERNAME: __token__
    # TWINE_PASSWORD: # Secret variable, see project CI settings.
  script:
    - twine upload dist/*
  environment:
    name: PyPI
    url: https://pypi.org/project/validata-table/$CI_COMMIT_TAG